name: "Build Workflow"

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
    

jobs:
  build:
    name: Build Next Js App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: node_version

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        