name: "Main Workflow"

on:
  pull_request:
    branches:
    - dev
    - main

jobs:
  build:
    name: Build The Project
    uses: ./.github/workflows/build.yaml
    with:
      node_version: 18

  code-scan:
    name: Scan The Project
    uses: ./.github/workflows/code-scan.yaml
    with:
      node_version: 18
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      G_TOKEN: ${{ secrets.G_TOKEN}}

  upload:
    name: Upload To S3
    needs: [build, code-scan]
    uses: ./.github/workflows/upload.yaml
    with:
      node_version: 18
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKETNAME: ${{ secrets.AWS_S3_BUCKETNAME }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
