name: "Upload Workflow"

on:
  workflow_call:

jobs:
  upload:
    name: Upload To S3
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync to S3
        uses: aws-actions/s3-sync@v2.2.6
        with:
          source-dir: './next'
          destination-s3-bucket: 'YOUR_BUCKET_NAME'
          destination-s3-prefix: ''
          bucket-owner-full-control: true